project:
  type: website
  output-dir: _site
  
website: 
  page-navigation: true
  favicon: img/icon.png
  reader-mode: false
  title: "Metaanalysis Website"
  sidebar:
    title: Metaanalysis Website
    logo: img/icon.svg
    tools: 
      - icon: envelope
        href: "mailto:david.matischek@edu.uni-graz.at"
      - icon: github
        href: https://github.com/saiko-psych
    contents: 
      - text: "Overview"
        href: index.qmd
      - text: "to-do"
        href: todo.qmd   
      - section: "Contents:"
        contents:
        - text: "About Page"
          href: about.qmd
        - text: "Summary"
          href: docs/short_summary.qmd
        - text: "Meta-Analysis Review"
          href: docs/meta_review.qmd
        - text: "Meta-Analysis Rating Sheet"
          href: docs/rating_sheet.qmd
        - text: "Matischek Study"
          href: docs/matischek_study.qmd
        - text: "Obrist Study"
          href: docs/obrist_study.qmd


execute:
  freeze: auto

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

    
    
